services:
    # Backend API
    - type: web
      name: preisenergie-backend
      runtime: python
      region: frankfurt
      plan: free
      buildCommand: |
          pip install --upgrade pip
          pip install -r requirements.txt
      startCommand: python run_server.py
      envVars:
          - key: PYTHON_VERSION
            value: 3.11.0
          - key: ENV
            value: production
          - key: PORT
            value: 10000 # Render uses this port
          - key: DATABASE_URL
            sync: false
          - key: ENTSOE_API_KEY
            sync: false
